# Generated by Django 2.2.5 on 2022-01-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220127_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='dheck_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='dommunication',
            new_name='communication',
        ),
    ]
